### ISSUE TITLE
influx error: ERROR i.m.influx.InfluxMeterRegistry - failed to send metrics to influx

### ISSUE THREAD

**Issue by nithinsridhar** [VictoriaMetrics/vmctl#11]
I configured in YML file like below:

management:
    metrics:
        export:
            influx:
                db: pizza
                step: '1m '
                uri: http://xxx:8086 

========================================
I'm running influxdb in GCP server and ip address and port is open to public and I access in grafana but it's thowring below error please help

[SpringContextShutdownHook] ERROR i.m.influx.InfluxMeterRegistry - failed to send metrics to influx
java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)

**Comment by hagen1778** [comment]
Hello @nithinsridhar!
Is the issue described above connected to `vmctl`?

**Comment by hagen1778** [comment]
Closing due to inactivity. Feel free to reopen.
