### ISSUE TITLE
InfluxDB 1.8.10 Import fails

### ISSUE THREAD

**Issue by fuslwusl** [VictoriaMetrics/vmctl#35]
I tried to migrate from influxdb v1.8 to victoriametrics using docker vmctl v1.81.2 on an ARM MacBook M1.
Connection is fine and the process starts but then aborts with following error:

`docker run victoriametrics/vmctl:v1.81.2 influx --influx-addr http://192.168.178.41:8086 --influx-user grafana --influx-database openhab_db --influx-chunk-size=500 --vm-addr http://192.168.178.41:8428 --vm-batch-size 2000
`
```
InfluxDB import mode
2022/09/21 10:35:10 Exploring scheme for database "openhab_db"
2022/09/21 10:35:10 fetching fields: command: "show field keys"; database: "openhab_db"; retention: "autogen"
2022/09/21 10:35:11 found 721 fields; skipped 116 non-numeric fields
2022/09/21 10:35:11 fetching series: command: "show series"; database: "openhab_db"; retention: "autogen"
2022/09/21 10:35:11 found 831 series
Found 721 timeseries to import. Continue? [Y/n] panic: EOF

goroutine 1 [running]:
main.prompt({0x400027ebd0, 0x29})
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmctl/utils.go:19 +0x1bc
main.(*influxProcessor).run(0x40002aed20, 0x0, 0x6b?)
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmctl/influx.go:47 +0xf4
main.main.func2(0x4000248240?)
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmctl/main.go:110 +0x494
github.com/urfave/cli/v2.(*Command).Run(0x4000248240, 0x40000b8240)
	github.com/urfave/cli/v2@v2.14.0/command.go:173 +0x5a8
github.com/urfave/cli/v2.(*App).RunContext(0x40001a7340, {0xa8ca90?, 0x4000028030}, {0x40000204e0, 0xd, 0xd})
	github.com/urfave/cli/v2@v2.14.0/app.go:384 +0xba0
github.com/urfave/cli/v2.(*App).Run(...)
	github.com/urfave/cli/v2@v2.14.0/app.go:253
main.main()
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmctl/main.go:227 +0xb6c


```

I also tried with different batch and chunk size limits and older versions of vmctl - but nothing worked - always ending with this error.

Does anybody know how to fix the problem?

**Comment by fuslwusl** [comment]
```bash
docker run victoriametrics/vmctl:v1.81.2 influx --influx-addr http://192.168.178.41:8086 --influx-user grafana --influx-database openhab_db --vm-addr http://192.168.178.41:8428 --influx-filter-series "from outdoortemp"
InfluxDB import mode
Exploring scheme for database "openhab_db"
...
Found 1 timeseries to import. Continue? [Y/n] 2022/10/02 22:03:06 found 1 series
panic: EOF

goroutine 1 [running]:
main.prompt({0x40002cc0f0, 0x27})
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmctl/utils.go:19 +0x1bc
main.(*influxProcessor).run(0x40002c09f0, 0x0, 0x6b?)
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmctl/influx.go:47 +0xf4
main.main.func2(0x40000006c0?)
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmctl/main.go:110 +0x494
github.com/urfave/cli/v2.(*Command).Run(0x40000006c0, 0x400002af00)
	github.com/urfave/cli/v2@v2.14.0/command.go:173 +0x5a8
github.com/urfave/cli/v2.(*App).RunContext(0x40001a7340, {0xa8ca90?, 0x4000028030}, {0x40000200c0, 0xc, 0xc})
	github.com/urfave/cli/v2@v2.14.0/app.go:384 +0xba0
github.com/urfave/cli/v2.(*App).Run(...)
	github.com/urfave/cli/v2@v2.14.0/app.go:253
main.main()
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmctl/main.go:227 +0xb6c
```

**Comment by hagen1778** [comment]
Hello! This repo has been moved and is no longer maintained. Please see https://github.com/VictoriaMetrics/vmctl
